# name = "cf-vless" # todo
# main = "vless-worker.js"

name = "cf-trojan" # todo
main = "trojan-worker.js"

compatibility_date = "2024-05-13"

[vars]
# https://rentry.co/CF-proxyIP
# 35.219.15.90 | Port:443 | CGK-Asia Pacific-Jakarta-49 ms
# 35.219.50.99 | Port:443 | CGK-Asia Pacific-Jakarta-50 ms
# 45.194.25.18 | Port:443 | CGK-Asia Pacific-Jakarta-88 ms
# 45.195.3.82 | Port:443 | CGK-Asia Pacific-Jakarta-51 ms
# 45.200.9.82 | Port:443 | CGK-Asia Pacific-Jakarta-61 ms
PASSWORD = "d9530b9f-9d4a-446c-987f-b4ea230e99f4"
PROXYIP = "45.200.9.82"
